name = "ipfsgateway"
usage_model = "bundled"
account_id = "2a94650a01a5a443da8d4210ab9beac6"
compatibility_flags = [
    "nodejs_compat",
    "transformstream_enable_standard_constructor",
    "streams_enable_constructors",
]
compatibility_date = "2022-08-04"
main = "dist/worker.js"

vars = { USE_WEB3STORAGE = true }

[build]
command = "npm run build"


# requires secret WEB3STORAGE_TOKEN and NFTSTORAGE_TOKEN if USE_WEB3STORAGE is false
# requires WEB3STORAGE_PK and WEB3STORAGE_PROOF for new w3up client
